### ISSUE TITLE
startSDK and stopSDK has no usage

### ISSUE THREAD

**Issue by huishan** [Viatick-co/bms-android-sdk-public#1]
Hi, 

According to the setup codes, startSDK and stopSDK that calls startBmsServivce and stopBmsService respectively has no usage at all. Is this intended? If not, when is the right time to call start and stop? Which view is supposed to be passed?

https://github.com/Viatick-co/bms-android-sdk-public/blob/6e34e9414f3953512c2010283e09f6369114d3ed/app/src/main/java/com/example/zanyk/bms_android_test_project/MainActivity.java#L35

**Comment by khoazany** [comment]
startBmsService and stopBmsService is used to start and stop beacon scanning. When and where it to be used is depends on the particular use case.
